name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: ${{ github.event.repository.name }}

      - name: Pull `unmanaged` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/unmanaged
          token: ${{ secrets.PAT }}
          path: unmanaged

      - name: Pull `collections` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/collections
          token: ${{ secrets.PAT }}
          path: collections

      - name: Pull `worlds` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/worlds
          token: ${{ secrets.PAT }}
          path: worlds

      - name: Pull `types` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/types
          token: ${{ secrets.PAT }}
          path: types

      - name: Pull `simulation` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/simulation
          token: ${{ secrets.PAT }}
          path: simulation

      - name: Pull `transforms` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/transforms
          token: ${{ secrets.PAT }}
          path: transforms
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Test project
        run: dotnet test "${{ github.event.repository.name }}/tests" -c Debug --logger "trx"

      - name: Publish Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          working-directory:  ${{ github.event.repository.name }}
          name: Report
          path: 'tests/TestResults/*.trx'
          reporter: dotnet-trx
          fail-on-error: false